name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.418

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="jellyfin-providersid-search-plugin-$tag"

          # Build everything
          dotnet build Jellyfin.Plugin.ProvidersIdSearch.csproj -c Release -o release

          zip -r "${release_name}.zip" release/*.dll

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              

          




